### ISSUE TITLE
doesn't install node versions

### ISSUE THREAD

**Issue by LorenzBischof** [pgilad/ansible-role-nvm#1]
I used this role without setting any variables and it didn't install the node version. Manually executing nvm install stable worked though. Am I doing anything wrong?

**Comment by LorenzBischof** [comment]
I don't exactly know why but if I remove sudo: yes then it works. I think if someone wants to install nvm in /usr/share then they can give the whole role sudo permissions. If you want I can create a pull request.

**Comment by pgilad** [comment]
Did you use it on localhost? I'm interested in the use-case and env, because installing this on an ubuntu box worked for me..

**edit**: can you try the vagrant version (`vagrant up`)?

**Comment by LorenzBischof** [comment]
Yes I am using localhost

**Comment by pgilad** [comment]
can you try the vagrant version?

**Comment by pgilad** [comment]
@lbischof Can you try running with `--sudo` ?

**Comment by LorenzBischof** [comment]
Same thing seems to happen in vagrant. I had to change the user to vagrant though because I can't ssh with root. 

Edit: it also happens if I set ansible.sudo = true

**Comment by pgilad** [comment]
Can you try it with `vagrant up` again (update to newest version). I made a fix for vagrant to use the vagrant user (instead of root)..

**Comment by pgilad** [comment]
Please let me know if it still doesn't work. Anyway using this locally requires sudo obviously
